FROM nginx:latest

COPY ./dist /usr/share/nginx/html
COPY ./src/assets/images /usr/share/nginx/html/src/assets/images

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]
