FROM openjdk:17
ARG JAR_FILE=RecLetter*.jar
WORKDIR /app
COPY /build/libs/${JAR_FILE} ./recletterBackend.jar
COPY /db/initdb.d /docker-entrypoint-initdb.d

ENTRYPOINT ["java", "-jar", "./recletterBackend.jar"]