FROM openjdk:17
ARG JAR_FILE=RecLetter*.jar
WORKDIR /app
COPY /build/libs/${JAR_FILE} ./recletterBackend.jar
CMD ["ln", "-sf", "/usr/share/zoneinfo/Asia/Seoul", "/etc/localtime"]
ENTRYPOINT ["java", "-jar", "./recletterBackend.jar"]