import os

from dotenv.main import load_dotenv

load_dotenv()
KAFKA_BOOTSTRAP_SERVERS = os.environ.get("KAFKA_BOOTSTRAP_SERVERS")

KAFKA_LETTER_REQUEST_TOPIC = os.environ.get("KAFKA_LETTER_REQUEST_TOPIC")
KAFKA_ASSET_DOWNLOADINFO_TOPIC = os.environ.get("KAFKA_ASSET_DOWNLOADINFO_TOPIC")
KAFKA_LETTER_ENCODINGINFO_TOPIC = os.environ.get("KAFKA_LETTER_ENCODINGINFO_TOPIC")
KAFKA_LETTER_RESULTINFO_TOPIC = os.environ.get("KAFKA_LETTER_RESULTINFO_TOPIC")


KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID = os.environ.get("KAFKA_LETTER_REQUEST_CONSUMER_GROUP_ID")
KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID = os.environ.get("KAFKA_ASSET_DOWNLOADINFO_CONSUMER_GROUP_ID")
KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID = os.environ.get("KAFKA_LETTER_ENCODINGINFO_CONSUMER_GROUP_ID")
KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID = os.environ.get("KAFKA_LETTER_RESULTINFO_CONSUMER_GROUP_ID")
KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID = os.environ.get("KAFKA_LETTER_RESULTINFO_DELETE_CONSUMER_GROUP_ID")